version: 2

before:
  hooks:
    - go mod tidy
    - go generate

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false
  replace_existing_draft: true
  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: replace
  header: |
    ## 🎉 Initial Release

    This is the first release of the Terraform Provider for n8n workflow automation platform.

    ### ✨ Features
    - **Workflow Management**: Create, update, and manage n8n workflows
    - **Credential Management**: Securely manage authentication credentials
    - **User Management**: Manage n8n users and permissions
    - **Project Management**: Organize workflows with projects
    - **LDAP Configuration**: Configure LDAP authentication
    - **Multi-Authentication**: Support for API key and basic authentication
    - **Security**: GPG-signed releases with comprehensive security checks

    ## Installation

    ### Terraform Registry

    ```hcl
    terraform {
      required_providers {
        n8n = {
          source  = "devops247-online/n8n"
          version = "{{ .Version }}"
        }
      }
    }

    provider "n8n" {
      base_url = "https://your-n8n-instance.com"
      api_key  = var.n8n_api_key
    }
    ```

    ### Manual Installation

    Download the appropriate binary for your platform from the attachments below and place it in your Terraform plugins directory.
  footer: |
    ## 📚 Documentation

    - [Provider Documentation](https://registry.terraform.io/providers/devops247-online/n8n/latest/docs)
    - [Usage Examples](https://github.com/devops247-online/terraform-provider-n8n/tree/main/examples)

    ## 🐛 Support

    If you encounter any issues, please report them at: https://github.com/devops247-online/terraform-provider-n8n/issues

changelog:
  use: git
  sort: asc
  abbrev: 0
  groups:
    - title: '🚀 Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: '📚 Documentation'
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 2
    - title: '🧹 Maintenance'
      regexp: '^.*?(chore|refactor)(\(.+\))??!?:.+$'
      order: 3
    - title: Other
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^ci:'
      - '^build:'
