version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
    volumes:
      - postgres_data_110:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"

  n8n:
    image: n8nio/n8n:1.1.0
    environment:
      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      
      # n8n 1.1.0 specific configuration
      N8N_USER_MANAGEMENT_DISABLED: false
      N8N_PUBLIC_API_DISABLED: false
      N8N_METRICS: true
      N8N_LOG_LEVEL: debug
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
      QUEUE_HEALTH_CHECK_ACTIVE: true
      N8N_ONBOARDING_FLOW_DISABLED: true
      N8N_DISABLE_UI: false
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      NODE_ENV: production
      
      # Force clean state for testing
      N8N_SKIP_OWNER_SETUP: false
      
      # Disable executions to speed up testing
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: none
      EXECUTIONS_DATA_SAVE_ON_ERROR: none
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: false
      
      # Security (for testing only)
      N8N_SECURE_COOKIE: false
      
      # Other settings
      GENERIC_TIMEZONE: UTC
      
    ports:
      - "5680:5678"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5678/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - n8n_data_110:/home/node/.n8n

volumes:
  postgres_data_110:
  n8n_data_110: