name: ✨ Feature Request
description: Request a new feature or enhancement to the Terraform n8n provider
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving the provider! Please describe the feature you'd like to see added.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature request fall into?
      options:
        - New resource type
        - New data source
        - Enhancement to existing resource
        - Provider configuration
        - Documentation improvement
        - Developer experience
        - Performance improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: |
        What problem are you trying to solve? What workflow is currently difficult or impossible?
        Please provide context about your use case and why this feature would be valuable.
      placeholder: |
        Describe the problem you're facing or the workflow you're trying to achieve.
        For example: "I need to manage n8n environment variables through Terraform but there's currently no resource for this."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented? Please be as specific as possible.
      placeholder: |
        Describe your ideal solution. Include:
        - What the feature should do
        - How it should work
        - Any specific configuration options
        - Example usage if applicable
    validations:
      required: true

  - type: textarea
    id: terraform-example
    attributes:
      label: Example Terraform Configuration
      description: |
        If applicable, provide an example of how you envision using this feature in Terraform.
        This helps us understand the desired user experience.
      placeholder: |
        # Example of how the feature might be used
        resource "n8n_new_resource" "example" {
          name = "example"
          # other configuration
        }
      render: hcl

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: |
        What alternatives have you considered? Why don't they work for your use case?
        This helps us understand the constraints and requirements better.
      placeholder: |
        Describe any workarounds you've tried or alternative approaches you've considered.
        For example: "I could manage this manually, but it doesn't fit with our IaC approach."

  - type: dropdown
    id: n8n-api-support
    attributes:
      label: n8n API Support
      description: Is this feature supported by the n8n API?
      options:
        - "Yes, n8n API supports this"
        - "No, would require n8n API changes"
        - "I'm not sure"
        - "Not applicable"
    validations:
      required: true

  - type: input
    id: n8n-api-reference
    attributes:
      label: n8n API Reference
      description: If you know the relevant n8n API endpoint(s), please provide links or references
      placeholder: "https://docs.n8n.io/api/... or describe the API endpoint"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for your use case?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve workflow"
        - "High - Blocking current project"
        - "Critical - Cannot proceed without this"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, links, or examples that would help us understand this request.

        Consider including:
        - Links to n8n documentation
        - Screenshots of n8n UI
        - Related issues or discussions
        - Community feedback or requests

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to the implementation?
      options:
        - label: I would be willing to contribute a pull request for this feature
          required: false
        - label: I would be available for testing and feedback during development
          required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
