name: 🏗️ New Resource Request
description: Request a new Terraform resource or data source for the n8n provider
title: "[RESOURCE] "
labels: ["new-resource", "enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in expanding the provider! Please provide details about the n8n resource you'd like to manage with Terraform.

  - type: dropdown
    id: resource-type
    attributes:
      label: Resource Type
      description: What type of Terraform component are you requesting?
      options:
        - Resource (manages infrastructure)
        - Data Source (reads existing infrastructure)
        - Both resource and data source
    validations:
      required: true

  - type: input
    id: resource-name
    attributes:
      label: Proposed Resource Name
      description: What should the resource be called in Terraform?
      placeholder: "n8n_environment_variable or data.n8n_execution"
    validations:
      required: true

  - type: textarea
    id: n8n-feature
    attributes:
      label: n8n Feature Description
      description: |
        What n8n feature or API endpoint would this resource manage?
        Please describe what this resource represents in n8n.
      placeholder: |
        Describe the n8n feature, for example:
        - Environment variables that can be used in workflows
        - Execution history and logs
        - Tags for organizing workflows
        - Community nodes installation
    validations:
      required: true

  - type: input
    id: n8n-api-endpoint
    attributes:
      label: n8n API Endpoint
      description: What n8n API endpoint(s) would be used?
      placeholder: "/api/v1/variables or /api/v1/executions"
    validations:
      required: true

  - type: input
    id: n8n-api-docs
    attributes:
      label: n8n API Documentation
      description: Link to relevant n8n API documentation
      placeholder: "https://docs.n8n.io/api/..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: |
        Why do you need this resource? What problem does it solve?
        How would you use it in your Terraform configurations?
      placeholder: |
        Describe your use case, for example:
        - "I need to manage environment variables as code alongside my workflows"
        - "I want to query execution history for monitoring and alerting"
        - "I need to automate the installation of community nodes"
    validations:
      required: true

  - type: textarea
    id: terraform-example
    attributes:
      label: Example Terraform Configuration
      description: |
        Provide an example of how you envision using this resource in Terraform.
        Include the resource block with typical attributes.
      placeholder: |
        resource "n8n_environment_variable" "db_connection" {
          key   = "DATABASE_URL"
          value = var.database_url
        }

        data "n8n_execution" "latest" {
          workflow_id = n8n_workflow.my_workflow.id
          limit       = 1
        }
      render: hcl
    validations:
      required: true

  - type: textarea
    id: resource-schema
    attributes:
      label: Proposed Resource Schema
      description: |
        What attributes should this resource have?
        Think about what fields you would configure and what would be computed.
      placeholder: |
        List the attributes, for example:
        - key (string, required) - The environment variable name
        - value (string, required, sensitive) - The environment variable value
        - id (string, computed) - The unique identifier
        - created_at (string, computed) - When it was created
    validations:
      required: true

  - type: dropdown
    id: crud-operations
    attributes:
      label: CRUD Operations Support
      description: Which operations does the n8n API support for this resource?
      multiple: true
      options:
        - Create
        - Read
        - Update
        - Delete
        - List/Query
    validations:
      required: true

  - type: textarea
    id: api-examples
    attributes:
      label: n8n API Examples
      description: |
        If you have examples of the n8n API requests/responses, please share them.
        This helps understand the data structure and available operations.
      placeholder: |
        GET /api/v1/variables
        {
          "data": [
            {
              "id": "1",
              "key": "DATABASE_URL",
              "value": "postgres://...",
              "createdAt": "2024-01-01T00:00:00Z"
            }
          ]
        }
      render: json

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this resource for your use case?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve workflow"
        - "High - Blocking current project"
        - "Critical - Cannot proceed without this"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any additional information that would help with implementation:
        - Special considerations
        - Dependencies on other resources
        - Relationship to existing resources
        - Links to community discussions

  - type: checkboxes
    id: research-done
    attributes:
      label: Research Checklist
      description: Please confirm you have done the following research
      options:
        - label: I have checked that this resource doesn't already exist in the provider
          required: true
        - label: I have verified the n8n API supports the operations needed
          required: true
        - label: I have reviewed the n8n documentation for this feature
          required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to the implementation?
      options:
        - label: I would be willing to contribute a pull request for this resource
          required: false
        - label: I would be available for testing and feedback during development
          required: false

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
